final List<String> allSupplies = [
'10 Blade',
'11 Blade',
'15 Blade',
'3DMax Light Mesh, Left, Medium, 3.1" x 5.3"',
'3DMax Light Mesh, Left, Size L, 4.1" x 6.2"',
'3DMax Light Mesh, Left, Size XL, 4.8" x 6.7"',
'3DMax Light Mesh, Right, Size L, 4.1" x 6.2"',
'3DMax Light Mesh, Right, Size M, 3.1" x 5.3"',
'3DMax Light Mesh, Right, Size XL, 4.8" x 6.7"',
'3DMax Mesh, Left, Extra-Large, 5" x 7"',
'3DMax Mesh, Left, Large, 4" x 6"',
'3DMax Mesh, Left, Medium, 3" x 5"',
'3DMax Mesh, Right, Extra-Large, 5" x 7"',
'3DMax Mesh, Right, Large, 4" x 6"',
'3DMax Mesh, Right, Medium, 3" x 5"',
'3DMax MID Mesh, Left, Extra-Large, 5" x 7"',
'3DMax MID Mesh, Left, Large, 4" x 6"',
'3DMax MID Mesh, Left, Medium, 3" x 5"',
'3DMax MID Mesh, Right, Extra-Large, 5" x 7"',
'3DMax MID Mesh, Right, Large, 4" x 6"',
'3DMax MID Mesh, Right, Medium, 3" x 5"',
'3M Heavy Duty Oscillating Blade, 19 mm x 0.96 mm (Stryker 5305-10-137)',
'3M Heavy Duty Oscillating Blade, 25 mm x 1.24 mm (Stryker 2108-151-006)',
'3M Heavy Duty Oscillating Blade, 25.4 mm x 0.97 mm (Stryker 5305-10-204)',
'3M Heavy Duty Oscillating Blade, Replaces 3M L 124 31.5m x 0.64 mm (Stryker 5305-10-124)',
'3M Heavy Duty Oscillating Blade, Replaces 3M L121 15.5 mm x 0.97 mm (Stryker 5305-10-121)',
'3M Heavy Duty Oscillating Blade, Replaces 3M L122 31.2 mm x 0.97 mm (Stryker 5305-10-122)',
'3M Heavy Duty Oscillating Blade, Replaces 3M L125 7.1 mm x 0.64 mm (Stryker 5305-10-125)',
'3M Heavy Duty Oscillating Blade, Replaces 3M L126 15.5 mm x 0.97 mm (Stryker 5305-10-126)',
'3M Heavy Duty Oscillating Blade, Replaces 3M L127 29.5 mm x 0.97 mm (Stryker 5305-10-127)',
'3M Heavy Duty Oscillating Blade, Replaces 3M L130 28.7 mm x 0.97 mm (Stryker 5305-10-130)',
'3M Heavy Duty Oscillating Blade, Replaces 3M L132 28.7 mm x 0.97 mm (Stryker 5305-10-132)',
'3M Heavy Duty Oscillating Blade, Replaces 3M L133 28.7 mm x 0.97 mm (Stryker 5305-10-133)',
'3M Heavy Duty Oscillating Blade, Replaces 3M L134 19.1 mm x 1.27 mm (Stryker 5305-10-134)',
'3M Heavy Duty Oscillating Blade, Replaces 3M L135 19.1 mm x 0.97 mm (Stryker 5305-10-135)',
'3M Heavy Duty Oscillating Blade, Replaces 3M L136 19.1 mm x 0.89 mm (Stryker 5305-10-136)',
'3M Heavy Duty Oscillating Blades, Replaces 3M L129 15.5 mm x 0.64 mm (Stryker 5305-10-129)',
'3M Ioban 2 Antimicrobial Incise Drapes',
'3M Ioban 2% CHG Incise Drapes',
'3M Isolation Steri-Drapes with Incise Film and Pouch',
'3M Prevena Restor Adapti-Form Incision Management System, 49 cm x 28 cm',
'77 x 135 in. Femoral Angiography Surgical Drape with Pouches',
'Abdominal Lithotomy Surgical Drape',
'AbsorbaTack ABS Wound Closure Fixation Device, 15 Tacks',
'AbsorbaTack Fixation Device with Flex Shaft, 30 Tacks',
'AbsorbaTack Fixation Device with Rigid Shaft, 30 Tacks',
'AbsorbaTack Fixation Device, 5 mm, One Use, 20 Tack',
'ABTHERA SENSAT.R.A.C. Open Abdomen Dressing',
'Accessories & Miscellaneous',
'ACM Cement Mixing Bowl Kit, Hi Vac',
'ACM Cement Mixing Bowl Kit, Hi Vac, 180 g cart',
'Advanced Cement Mixing Kit Bowl',
'Advanced Cement Mixing Kit with 206-512 Femoral Breakaway Nozzle',
'Advanced Cement Mixing Kit with Cartridge and Nozzle',
'Advanced Cement Mixing System with Nozzle and Pressurizer',
'Angiography & Cardiovascular',
'Aquamantys Bipolar Sealers',
'Average Medium Blade, 9 mm x 25 mm x 0.38 mm (Stryker 2296-3-111)',
'Bariatric Surgical Drape with Pouches',
'BD ChloraPrep Hi-Lite Orange 26 mL Skin Prep Applicator with Sterile Solution',
'BD ChloraPrep Scrub Teal 26 mL Skin Prep Applicator with Sterile Solution',
'Bend-a-Beam Single-Function Malleable ABC Hand Control Handpiece, 6"',
'Bend-a-Beam Single-Function Malleable ABC Hand Control Handpiece, 9"',
'Bilateral OrthoMax Extremity Surgical Drapes',
'Biogel Indicator Surgical Undergloves, Powder Free, Size 5.5 (green under)',
'Biogel Indicator Surgical Undergloves, Powder Free, Size 6 (green under)',
'Biogel Indicator Surgical Undergloves, Powder Free, Size 6.5 (green under)',
'Biogel Indicator Surgical Undergloves, Powder Free, Size 7 (green under)',
'Biogel Indicator Surgical Undergloves, Powder Free, Size 8 (green under)',
'Biogel Indicator Surgical Undergloves, Powder Free, Size 8.5 (green under)',
'Biogel Latex Surgical Gloves, Powder-Free, Size 5.5(green)',
'Biogel Latex Surgical Gloves, Powder-Free, Size 6(green)',
'Biogel Latex Surgical Gloves, Powder-Free, Size 6.5(green)',
'Biogel Latex Surgical Gloves, Powder-Free, Size 7(green)',
'Biogel Latex Surgical Gloves, Powder-Free, Size 7.5(green)',
'Biogel Latex Surgical Gloves, Powder-Free, Size 8(green)',
'Biogel Latex Surgical Gloves, Powder-Free, Size 8.5(green)',
'Biogel Latex Surgical Gloves, Powder-Free, Size 9(green)',
'Biogel PI Micro Indicator Undergloves, Size 5.5(blue)',
'Biogel PI Micro Indicator Undergloves, Size 6(blue)',
'Biogel PI Micro Indicator Undergloves, Size 7(blue)',
'Biogel PI Micro Indicator Undergloves, Size 7.5(blue)',
'Biogel PI Micro Indicator Undergloves, Size 8(blue)',
'Biogel PI Micro Indicator Undergloves, Size 8.5(blue)',
'Biogel PI Micro Indicator Undergloves, Size 9(blue)',
'Biogel PI Pro-Fit Sterile Powder-Free Synthetic Surgical Gloves, Size 6 (brown)',
'Biogel PI Pro-Fit Sterile Powder-Free Synthetic Surgical Gloves, Size 6.5 (brown)',
'Biogel PI Pro-Fit Sterile Powder-Free Synthetic Surgical Gloves, Size 7 (brown)',
'Biogel PI Pro-Fit Sterile Powder-Free Synthetic Surgical Gloves, Size 7.5 (brown)',
'Biogel PI Pro-Fit Sterile Powder-Free Synthetic Surgical Gloves, Size 8 (brown)',
'Biogel PI Pro-Fit Sterile Powder-Free Synthetic Surgical Gloves, Size 8.5 (brown)',
'Biogel PI Pro-Fit Sterile Powder-Free Synthetic Surgical Gloves, Size 9 (brown)',
'Biogel PI UltraTouch Sterile Powder-Free Synthetic Surgical Gloves, Size 5.5(yellow)',
'Biogel PI UltraTouch Sterile Powder-Free Synthetic Surgical Gloves, Size 6(yellow)',
'Biogel PI UltraTouch Sterile Powder-Free Synthetic Surgical Gloves, Size 6.5(yellow)',
'Biogel PI UltraTouch Sterile Powder-Free Synthetic Surgical Gloves, Size 7(yellow)',
'Biogel PI UltraTouch Sterile Powder-Free Synthetic Surgical Gloves, Size 7.5(yellow)',
'Biogel PI UltraTouch Sterile Powder-Free Synthetic Surgical Gloves, Size 8(yellow)',
'Biogel PI UltraTouch Sterile Powder-Free Synthetic Surgical Gloves, Size 8.5(yellow)',
'Biogel PI UltraTouch Sterile Powder-Free Synthetic Surgical Gloves, Size 9(yellow)',
'Biomet Bone Cement R 1X40',
'Bipolar Cautery Cord, Sterile',
'Blunt Electrolase Tip, Sterile',
'Bone Wax, Suture, 2.5 g',
'C-Section, OB/GYN & Lithotomy',
'Cancellous Chip Graft, 1 mm to 4 mm, 5 cc-30cc',
'Cancellous Chip Graft, 4 mm to 10 mm, 10 cc-30cc',
'Carl Zeiss Microscope Drape (Manufacturer: Carl Zeiss Inc.)',
'Cautery Pushbutton Pencil Holster ( bovie )',
'Cautery Tip Cleaner',
'Cesarean Section Surgical Drape with Pouch',
'Cesarean Section Surgical Drape with Pouch and Fenestration',
'Cesarean-Section Sheets and Pouch with Incise Film',
'Channel Round Silicone Drain with Trocar, 15 Fr, 3/16", Full Fluted',
'Channel Round Silicone Drain with Trocar, 19 Fr, 1/4", Full Fluted',
'Channel Round Silicone Drain, 10 Fr, 1/8", Full Fluted',
'Channel Round Silicone Drain, 15 Fr, 3/16", Full Fluted',
'Channel Round Silicone Drain, 15 Fr, 3/16", Full Fluted, Bendable Trocar',
'Channel Round Silicone Drain, 19 Fr, 1/4", Full Fluted',
'Channel Round Silicone Drain, 24 Fr, 5/16", Full Fluted',
'Circular Bags with Elastic Bands (Manufacturer: Medline)',
'Clearify Visualization System',
'COMMAND2 Oscillating and Sagittal Saw Blade, 7.0 mm x 18.5 mm x 0.51 mm (Stryker 2296-33-114)',
'COMMAND2 Oscillating and Sagittal Saw Blade, 9.0 mm x 0.51 mm x 25.0 mm (Stryker 2296-33-111)',
'COMMAND2 Oscillating and Sagittal, Saw Blade, 9.0 mm x 31 mm x 0.51 mm (Stryker 2296-33-125)',
'CORE Oscillating Saw Blade Crescentic 9.0 mm x.38 mm x 12 mm (Stryker 5400-31-170)',
'CORE Oscillating Saw Precision, Ultra Thin Oral 5.0 mm x 0.38 mm x 12.0 mm (Stryker 5400-031-052)',
'CORE Oscillating Saw Precision, Ultra Thin Oral 9.0 mm x 0.38 mm x 12.0 mm (Stryker 5400-031-050)',
'CORE Oscillating Saw, Precision Ultra Thin Oral 11.5 mm x 0.64 mm x 12.0 mm (Stryker 5400-031-054)',
'CORE Oscillating Saw, Precision Ultra Thin Oral 11.5 mm x 0.64 mm x 7.0 mm (Stryker 5400-031-053)',
'Craniotomy T Surgical Drape with Pouch',
'Crescentic Oscillating Saw Blade, 15 mm x 0.51 mm x 30 mm (Stryker 2296-031-416)',
'CV Split Surgical Drape with Clear Anesthesia Screen',
'Da Vinci X/Xi 12 mm Stapler Cannula',
'Da Vinci X/Xi 8 mm Bladeless Optical Obturator',
'Da Vinci X/Xi 8 mm Cannula (Long)',
'Da Vinci X/Xi 8 mm Cannula (Short)',
'Da Vinci X/Xi Black Diamond Micro Forceps',
'Da Vinci X/Xi Cadiere Forceps',
'Da Vinci X/Xi Cannula Seal (12 mm)',
'Da Vinci X/Xi Cannula Seal (8 mm)',
'Da Vinci X/Xi Cobra Grasper',
'Da Vinci X/Xi Column Drape',
'Da Vinci X/Xi Curved Bipolar Dissector',
'Da Vinci X/Xi DeBakey Forceps',
'Da Vinci X/Xi Dual Blade Retractor',
'Da Vinci X/Xi EndoWrist Suction Irrigator',
'Da Vinci X/Xi Fenestrated Bipolar Forceps',
'Da Vinci X/Xi Force Bipolar',
'Da Vinci X/Xi Harmonic ACE Curved Shears',
'Da Vinci X/Xi Hot Shears (Monopolar Curved Scissors)',
'Da Vinci X/Xi Large Needle Driver',
'Da Vinci X/Xi Long Bipolar Grasper',
'Da Vinci X/Xi Long Tip Forceps',
'Da Vinci X/Xi Maryland Bipolar Forceps',
'Da Vinci X/Xi Mega Needle Driver',
'Da Vinci X/Xi Micro Bipolar Forceps',
'Da Vinci X/Xi Patient Cart Arm Drape',
'Da Vinci X/Xi Permanent Cautery Hook',
'Da Vinci X/Xi Permanent Cautery Spatula',
'Da Vinci X/Xi Potts Scissors',
'Da Vinci X/Xi ProGrasp Forceps',
'Da Vinci X/Xi Resano Forceps',
'Da Vinci X/Xi Round Tip Scissors',
'Da Vinci X/Xi Small Graptor',
'Da Vinci X/Xi Stapler 30 Grey Reload',
'Da Vinci X/Xi Stapler 30 White Reload',
'Da Vinci X/Xi SureForm 45 Black Reload',
'Da Vinci X/Xi SureForm 45 Blue Reload',
'Da Vinci X/Xi SureForm 45 Green Reload',
'Da Vinci X/Xi SureForm 45 Grey Reload',
'Da Vinci X/Xi SureForm 45 White Reload',
'Da Vinci X/Xi SynchroSeal',
'Da Vinci X/Xi Tenaculum Forceps',
'Da Vinci X/Xi Vessel Sealer Extend',
'DePuy CMW 1 Bone Cement, 20g',
'DePuy CMW 1 Bone Cement, 40g',
'DePuy CMW 1 GENTAMICIN Bone Cement, 20g',
'DePuy CMW 1 GENTAMICIN Bone Cement, 40g',
'DePuy CMW 2 Bone Cement, 20g',
'DePuy CMW 2 Bone Cement, 40g',
'DePuy CMW 2 GENTAMICIN Bone Cement, 20g',
'DePuy CMW 2 GENTAMICIN Bone Cement, 40g',
'DePuy CMW 3 Bone Cement, 20g',
'DePuy CMW 3 Bone Cement, 40g',
'DePuy CMW 3 GENTAMICIN Bone Cement, 20g',
'DePuy CMW 3 GENTAMICIN Bone Cement, 40g',
'Disposable Covers for Exergen TAT-2000 and TAT-5000 Scanners (Manufacturer: Exergen Corporation)',
'Disposable Sharp Electrolase Tip, Sterile',
'Duraprep Solution with Applicator, 26 mL',
'Eclipse Ultrasound Probe Covers (Manufacturer: Parker Labs Inc.)',
'Electrolase, Blunt, N-Ster',
'Endopath Bladeless Trocar with Smooth Sleeve, Handled, 100 mm Length, 5 mm',
'Endopath Bladeless Trocar with Stability Sleeve, Nonhandled, Orange, 5 mm x 75 mm',
'ENDOPATH Dilating Tip Trocar with Stability Sleeve, 100 mm Length, Orange, 5.0 mm (Ethicon 355LD)',
'ENDOPATH Dilating Tip Trocar with Stability Sleeve, 100 mm Length, Purple, 10/12 mm (Ethicon 512SD)',
'Endopath Dilating Tip Trocar with Stability Sleeve, Orange, 5 mm (Ethicon 355LD)',
'Endopath Dilating Tip Trocar with Stability Sleeve, Orange, 5 mm x 75 mm',
'Endopath Dilating Tip Trocar with Stability Sleeve, Purple, 10/12 mm x 100 mm (Ethicon 512SD)',
'Endopath Xcel Bladeless Trocar with Optiview Technology, 5 mm x 100 mm',
'Endopath Xcel Bladeless Trocar with Optiview Technology, 5 mm x 150 mm',
'Endopath Xcel Bladeless Trocar with Optiview Technology, 5 mm x 75 mm',
'Endopath Xcel Bladeless Trocar with Smooth Sleeve, Handled, Teal, 5 mm x 100 mm',
'Endopath Xcel Bladeless Trocar with Smooth Sleeve, Teal, 11 mm x 100 mm',
'Endopath Xcel Bladeless Trocar with Smooth Sleeve, Teal, 12 mm x 100 mm',
'Endopath Xcel Bladeless Trocar with Stability Sleeve, 12 mm x 100 mm',
'Endopath Xcel Bladeless Trocar with Stability Sleeve, 12 mm x 150 mm',
'Endopath Xcel Bladeless Trocar with Stability Sleeve, 12 mm x 75 mm',
'Endopath Xcel Bladeless Trocar with Stability Sleeve, 5 mm x 100 mm',
'Endopath Xcel Bladeless Trocar with Stability Sleeve, 5 mm x 150 mm',
'Endopath Xcel Bladeless Trocar with Stability Sleeve, 5 mm x 75 mm',
'Endopath Xcel Bladeless Trocar with Stability Sleeve, Handled, Teal, 12 mm x 100 mm',
'Endopath Xcel Bladeless Trocar with Stability Sleeve, Handled, Teal, 15 mm x 100 mm',
'Endopath Xcel Bladeless Trocar with Stability Sleeve, Teal, 11 mm x 100 mm',
'Endopath Xcel Bladeless Trocar with Stability Sleeve, Teal, 8 mm x 100 mm',
'Endopath Xcel Blunt Tip Trocar with Smooth Sleeve and Adjustable Plug, Purple, 12 mm x 100 mm (Ethicon H12LP)',
'ENDOPATH Xcel Blunt Tip Trocar with Smooth Sleeve and Adjustable Plug, Purple, 12 mm x 100 mm (Ethicon H12LP)',
'ENDOPATH Xcel Dilating Tip Trocar with Stability Sleeve, Gold, 11 mm x 100 mm (Ethicon D11LT)',
'ENDOPATH Xcel Dilating Tip Trocar with Stability Sleeve, Gold, 12 mm x 100 mm (Ethicon D12LT)',
'ENDOPATH Xcel Dilating Tip Trocar with Stability Sleeve, Gold, 12 mm x 150 mm (Ethicon D12XT)',
'Endopath Xcel Dilating Tip Trocar with Stability Sleeve, Gold, 5 mm x 100 mm (Ethicon D5LT)',
'ENDOPATH Xcel Dilating Tip Trocar with Stability Sleeve, Gold, 5.0 mm x 100 mm (Ethicon D5LT)',
'ENDOPATH Xcel Dilating Tip Trocar with Stability Sleeve, Gold, 5.0 mm x 75 mm (Ethicon D5ST)',
'Endopath Xcel Dilating Tip Trocar, 75 mm (Ethicon D5ST)',
'Endopath Xcel Dilating Tip Trocar, Gold, 12 mm Diameter, 150 mm Shaft (Ethicon D12XT)',
'Endopath Xcel Trocar with Stability Sleeve, Gold, 11 mm x 100 mm (Ethicon D11LT)',
'Extra-Large Surgical Mayo Stand Covers (Manufacturer: Medline)',
'Femoral Angiography Drape with Pouches',
'Fluid Collection System',
'Foam Dressing Kit with Fitted Pads, Size L ( Black )',
'Foam Dressing Kit with Fitted Pads, Size M ( Black)',
'Foam Dressing Kit with Fitted Pads, Size S ( Black )',
'General Drape Sheets',
'Halyard Mayo Stand Covers (Manufacturer: Halyard Health, Inc.)',
'Head Turban Surgical Drape',
'Heated High-Flow Tube Set for PneumoClear Insufflator',
'Heated/Humidified Smoke Evacuation Tube for PneumoClear Insufflator',
'Heavy Duty Oscillating Blade, 15.5 mm x 61.5 mm x 0.64 mm (Stryker 5305-10-123)',
'Hibiclens Antiseptic Skin Cleanser, Foam, 4 oz. Wide Neck Pack with Pump',
'Humeral Nozzle for Advanced Cement Mixing (ACM) System',
'Insufflation Needle, Endopath, 14G, 15 cm',
'Insufflation Tubing with 12 mm Connecto',
'Insufflation Tubing with 22 mm Connector',
'Insufflation Tubing with CPC Connector',
'Insufflation Tubing with Push-On Connector',
'Insufflation Tubing with Rotating Connector',
'Invisishield Incise Surgical Drapes',
'Invisishield Isolation Incise Surgical Drape',
'Invisishield Mini C-Arm Surgical Drapes (Manufacturer: Medline)',
'Laparoscopic Suture and Hernia Grasper (carter thompson)',
'Laparotomy & Abdominal Drapes',
'Laparotomy Surgical T-Drape with Incise and Instrument Pad',
'Laparotomy Surgical T-Drape with Instrument Pad',
'LigaSure Maryland Jaw Thoracic Sealer/Divider',
'LigaSure Small Jaw Instrument, Sterile',
'LigaSure XP Maryland Jaw Sealer-divider with Nano-coating, Latching Handle, Shaft Length 23 cm',
'LigaSure XP Maryland Jaw Sealer-divider with Nano-coating, Latching Handle, Shaft Length 37 cm',
'LigaSure XP Maryland Jaw Sealer-divider with Nano-coating, Latching Handle, Shaft Length 44 cm',
'LigaSure XP Maryland Jaw Sealer-divider with Nano-coating, One-step Sealing, Shaft Length 23 cm',
'LigaSure XP Maryland Jaw Sealer-divider with Nano-coating, One-step Sealing, Shaft Length 37 cm',
'LigaSure XP Maryland Jaw Sealer-divider with Nano-coating, One-step Sealing, Shaft Length 44 cm',
'Lithotomy Surgical Drape with Attached Leggings',
'LOOP,VESSEL,BLUE,MINI,NS',
'Magnetic Instrument Mats (Manufacturer: Medline)',
'Major Abdominal Surgical Drape with Pouches',
'Mako Blade - Narrow 2 mm (Stryker 116171)',
'Mako Blade - Standard 2 mm Standard (Stryker 116170)',
'Manufacturer: ASPEN SURGICAL PRODUCTS',
'Maryland Jaw Laparoscopic Device, 23 cm',
'Maryland Jaw Laparoscopic Device, 37 cm',
'Maryland Jaw Laparoscopic Device, 44 cm',
'Medline Full-Size C-Arm Surgical Drapes (Manufacturer: Medline)',
'Medline Ultrasound Probe Covers Kits (Manufacturer: Medline)',
'MESH,POLYPROPYLENE,SELF-GRIPPING,20X15CM',
'MESH,POLYPROPYLENE,SELF-GRIPPING,30X20CM',
'MESH,POLYPROPYLENE,SELF-GRIPPING,30X30CM',
'MESH,POLYPROPYLENE,SELF-GRIPPING,40X30CM',
'MESH,PROGRIP,SELFGRIP,POLYPROP,15CMX15CM',
'Micro Dual Cut Oscillating Sagittal, Saw Blade, 31.0 mm x 9.0 mm x 0.5 mm (Stryker 5400-3-125)',
'Micro Oscillating and Sagittal Saw 13 mm x 0.51 mm x 34.5 mm (Stryker 2296-33-106)',
'Micro Oscillating and Sagittal Saw 2.5 mm x.51 mm x 18 mm (Stryker 2296-33-413)',
'Micro Oscillating and Sagittal Saw 6.5 mm x 0.51 mm x 18.5 mm (Stryker 2296-33-51)',
'Micro Oscillating and Sagittal Saw Blade, 9.0 mm x 0.38 mm x 18 mm (Stryker 2296-3-530)',
'Micro Oscillating and Sagittal Saw Blade, 9.0 mm x 25 mm x 0.51 mm (Stryker 2296-33-521)',
'Micro Oscillating and Sagittal Saw Blade, Aggressive Thin Blade 5.5 mm x 0.38 mm x 25.0 mm (Stryker 2296-3-524)',
'Micro Oscillating and Sagittal Saw Blade, Cut Thickness 0.38 mm 6.5 mm x 18.5 mm (Stryker 2296-3-51)',
'Micro Oscillating and Sagittal Saw Blade, Precision Thin Blade Teeth per cm: 22 9.0 mm x 18.5 mm x 0.38 mm (Stryker 2296-3-255)',
'Micro Oscillating and Sagittal Saw Blade, Precision Thin Blade Teeth per cm: 7 19.5 mm x 41 mm x 0.38 mm (Stryker 2296-3-254)',
'Micro Oscillating and Sagittal Saw Blade, Precision Thin Blade with 10 mm Depth Stop 9.0 mm x 10 mm x 0.38 mm (Stryker 2296-3-101)',
'Micro Oscillating and Sagittal Saw Blade, Teeth per cm: 12.6 5.5 mm x 11.5 mm x 0.51mm (Stryker 2296-33-410)',
  'Micro Oscillating and Sagittal Saw, Aggressive Thin Blade, 13.4 mm x 0.38 mm x 39 mm (Stryker 2296-3-515)',
  'Micro Oscillating and Sagittal Saw, Aggressive Thin Blade, 9 mm x 0.38 mm x 4 mm (Stryker 2296-3-526)',
  'Micro-Oscillating Saw, Precision Thin Blade, 5.5 mm x 0.38 mm (Stryker 296-31-414)',
  'Microtek Banded Bags (Manufacturer: Various)',
  'Microtek C-Arm Drapes (Manufacturer: Microtek Medical Inc.)',
  'Microtek Drapes for Leica Microscopes (Manufacturer: Microtek Medical Inc.)',
  'Microtek Drapes for Zeiss Surgical Microscopes (Manufacturer: Microtek Medical Inc.)',
  'Microtek ORS Hush Slush System Drapes (Manufacturer: Various)',
  'Microtek Probe Covers (Manufacturer: Microtek Medical Inc.)',
  'Microscope Drapes',
  'Monopolar Cord, Sterile, Green',
  'Nonsterile Foot Switch Surgical Equipment Drape (Manufacturer: Medline)',
  'Nonsterile Surgical Drain Bag Pouches',
  'Ophthalmic, EENT & Neuro',
  'OPMI Drapes with VisionGuard Lenses (Manufacturer: Carl Zeiss Inc.)',
  'OrthoMax Extremity Surgical Drape',
  'Orthopedic & Extremity Drapes',
  'Oscillating Sagittal Blade, 9 mm x 31 mm x 0.38 mm (Stryker 2296-3-525)',
  'Palacos R High-Viscosity Bone Cement, 40 g',
  'Palacos R Pro High-Viscosity Bone Cement, All-in-One Fixation System, Net 75 g',
  'Palacos R+G High-Viscosity Bone Cement with Gentamicin, 40 g',
  'Palacos R+G Pro High-Viscosity Bone Cement with Gentamicin, All-in-One Fixation System, Net 75 g',
  'Parietene Progrip Self-Fixing Mesh, 15 x 9 cm',
  'Parietene Progrip Self-Fixing Mesh, Left Side, 12 x 8 cm',
  'Parietene Progrip Self-Fixing Mesh, Right Side, 12 x 8 cm',
  'Passor Sterile Suture, Two Guides (10-12 and 15 mm), Two Trocar Swabs (5-8 and 10-12 mm) (carter thompson)',
  'Pediatric Laparotomy Surgical Drape',
  'PerFix Plug Surgical Mesh, Extra-Large, 1.6" x 2"',
  'PerFix Plug Surgical Mesh, Large, 1.6" x 1.9"',
  'PerFix Plug Surgical Mesh, Medium, 1.3" x 1.55"',
  'PerFix Plug Surgical Mesh, Small, 1" x 1.35"',
  'PneumoClear Tube Set, High Flow',
  'ProGrip Laparoscopic Self-Fixating Mesh, 10 cm x 15 cm',
  'ProGrip Laparoscopic Self-Fixating Mesh, Right Anatomical, 10 cm x 15 cm',
  'ProGrip Mesh, Size L, 16 x 12 cm, Left Anatomical',
  'ProGrip Mesh, Size L, 16 x 12 cm, Right Anatomical',
  'PROTEXIS Latex Ortho Surgical Gloves, Size 6 (brown)',
  'PROTEXIS Latex Ortho Surgical Gloves, Size 6.5 (brown)',
  'PROTEXIS Latex Ortho Surgical Gloves, Size 7 (brown)',
  'PROTEXIS Latex Ortho Surgical Gloves, Size 7.5 (brown)',
  'PROTEXIS Latex Ortho Surgical Gloves, Size 8 (brown)',
  'PROTEXIS Latex Ortho Surgical Gloves, Size 8.5 (brown)',
  'PROTEXIS Latex Ortho Surgical Gloves, Size 9 (brown)',
  'Protexis PI Ortho Surgical Gloves, Size 6 (whites)',
  'Protexis PI Ortho Surgical Gloves, Size 6.5 (whites)',
  'Protexis PI Ortho Surgical Gloves, Size 7 (whites)',
  'Protexis PI Ortho Surgical Gloves, Size 7.5 (whites)',
  'Protexis PI Ortho Surgical Gloves, Size 8 (whites)',
  'Protexis PI Ortho Surgical Gloves, Size 8.5 (whites)',
  'Protexis PI Ortho Surgical Gloves, Size 9 (whites)',
  'Protexis™ PI Blue with Neu-Thera™ Coating Size 5.5',
  'Protexis™ PI Blue with Neu-Thera™ Coating Size 6',
  'Protexis™ PI Blue with Neu-Thera™ Coating Size 6.5',
  'Protexis™ PI Blue with Neu-Thera™ Coating Size 7',
  'Protexis™ PI Blue with Neu-Thera™ Coating Size 7.5',
  'Protexis™ PI Blue with Neu-Thera™ Coating Size 8',
  'Protexis™ PI Blue with Neu-Thera™ Coating Size 8.5',
  'Protexis™ PI Blue with Neu-Thera™ Coating Size 9',
  'Proxima Sterile Surgical Mayo Stand Covers (Manufacturer: Medline)',
  'PTFE-Coated Cautery Electrode, 2.50", Blade Tip',
  'PTFE-Coated Cautery Electrode, 2.50", Modified Blade Tip with Extended Insulation',
  'PTFE-Coated Cautery Electrode, 2.75", Blade Tip',
  'PTFE-Coated Cautery Electrode, 2.75", Modified Blade Tip with Extended Insulation',
  'PTFE-Coated Cautery Electrode, 2.75", Modified Needle Tip with Extended Insulation',
  'PTFE-Coated Cautery Electrode, 2.75", Needle Tip',
  'PTFE-Coated Cautery Electrode, 4.00", Blade Tip',
  'PTFE-Coated Cautery Electrode, 4.00", Modified Blade Tip with Extended Insulation',
  'PTFE-Coated Cautery Electrode, 4.00", Modified Needle Tip with Extended Insulation',
  'PTFE-Coated Cautery Electrode, 6", Blade Tip',
  'PTFE-Coated Cautery Electrode, 6", Modified Blade Tip',
  'PTFE-Coated Cautery Needle, 6", Modified Needle with Extended Insulation',
  'Rectangular Bags with Elastic Bands (Manufacturer: Medline)',
  'Refurbished Stryker System 6 Saw Blade, 13 mm x 90 mm x 1.27 mm (6113-127-090)',
  'Robotic Arm Drape (Manufacturer: Medline)',
  'Sanitary MRI Headset Covers (Manufacturer: Newmatic Medical)',
  'Saw Blade System 6, 90 mm x 25 mm x 1.27 (Stryker 6125-127-090)',
  'Securestrap Fixation Device, Sterile, 5 mm',
  'Securestrap Fixation Device, Strap, Absorbable, 5mm',
  'Silicone Cautery Electrode, 2.50", Blade Tip',
  'Silicone Cautery Electrode, 2.75", Blade Tip',
  'Silicone Cautery Electrode, 2.75", Blade Tip with Extended Insulation',
  'Silicone Cautery Electrode, 2.80", Needle Tip',
  'Silicone Cautery Electrode, 4.00", Blade Tip',
  'Silicone Cautery Electrode, 4.00", Blade Tip with Extended Insulation',
  'Silicone Cautery Electrode, 4.00", Blade Tip with Extended Insulation, Safety Sleeve',
  'Silicone Cautery Electrode, 6.50", Blade Tip',
  'Silicone Cautery Electrode, 6.50", Blade Tip with Extended Insulation',
  'Silicone Cautery Electrode, 6.50", Needle Tip with Extended Insulation',
  'Silicone Suction Reservoir for Closed Wound Drainage, 100 cc Capacity',
  'Skin Marker with Ruler, Dual Fine and Regular Tip, Utility',
  'Skin Scrub Tray, Wet, Standard',
  'Small Oscillating Saw Blade, with 10 mm ACL Stop 9.0 mm x 18.5 mm x 0.51 mm (Stryker 2296-33-101)',
  'SMARTSET GHV Gentamicin Bone Cement, 20g',
  'SMARTSET GHV Gentamicin Bone Cement, 40g',
  'SMARTSET GMV ENDURANCE Gentamicin Bone Cement, 40g',
  'SMARTSET HV Bone Cement, 20g',
  'SMARTSET HV Bone Cement, 40g',
  'SMARTSET MV ENDURANCE Bone Cement, 20g',
  'SMARTSET MV ENDURANCE Bone Cement, 40g',
  'Specialized Covers',
  'Steri-Drape 1003 Isolation Bags (Manufacturer: 3M)',
  'Steri-Drape Incise Drape',
  'Steri-Drape Isolation Drapes with Incise Film',
  'Steri-Drape with Adhesive Aperture',
  'Sterile C-Section Drape with Viewing Window',
  'Sterile Cardiovascular Surgical Drape',
  'Sterile Craniotomy Surgical Drape with Pouch',
  'Sterile CVMax Cardiovascular Incise Surgical Drape',
  'Sterile Eye Surgical Drapes with Fenestrated Incise and Pouch',
  'Sterile Femoral Angiography Surgical Drapes',
  'Sterile Full Surgical Drapes',
  'Sterile Large Surgical Drape Sheets',
  'Sterile Medium Surgical Drape Sheets',
  'Sterile Ophthalmic Surgical Drapes with Separate Incise',
  'Sterile Pitcher Tray, 1,200 mL',
  'Sterile Reinforced Surgical Table Cover',
  'Sterile Rigid Yankauer with Flange Tip, No Vent',
  'Sterile Rigid Yankauer with Poole Tip',
  'Sterile Standard Extremity Surgical Drape',
  'Sterile Standard Film Sheet Drapes',
  'Sterile Three-Quarter Reinforced Surgical Drape Sheets 3/4',
  'Sterile Three-Quarter Surgical Drape Sheets 3/4',
  'Sterile Three-Quarter Surgical Drape Sheets with Reverse Fold 3/4',
  'Sterile Yankauer Suction Instrument with Bulb/Ball Tip, No Vent',
  'Sterion Maxi Vessel Loop, Blue, 1 mm x 406 mm',
  'Sterion Maxi Vessel Loop, Blue, 1 mm x 762 mm',
  'Sterion Maxi Vessel Loop, Blue, Sterile, 1 mm x 406 mm',
  'Sterion Maxi Vessel Loop, Red, Sterile, 1 mm x 406 mm',
  'Sterion Maxi Vessel Loop, White, 1 mm x 76 mm',
  'Sterion Maxi Vessel Loop, White, Sterile',
  'Sterion Maxi Vessel Loop, Yellow',
  'Sterion Maxi Vessel Loop, Yellow, Sterile',
  'Sterion Micro Maxi Vessel, Sterile, Red',
  'Sterion Micro Mini Vessel Loop, Blue, Sterile, 0.8 mm x 406 mm',
  'Sterion Micro Mini Vessel Loop, Red, Sterile',
  'Sterion Micro Mini Vessel Loop, White, Sterile, 0.8 mm x 406 mm',
  'Sterion Micro Mini Vessel Loop, Yellow, Sterile, 0.8 mm x 406 mm',
  'Sterion Micro Mini Vessel, Sterile, Blue',
  'Sterion Micro Mini Vessel, Sterile, Blue, 30"',
  'Sterion Micro Mini Vessel, Sterile, Red, 30"',
  'Sterion Super Maxi Vessel Loop',
  'Sterion Super Maxi Vessel Loop, Sterile, 1.3 mm x 559 mm',
  'Sterion Vessel Loop',
  'Sternum Saw (course Tooth) 28.5 mm x 0.70 mm x 6.12 mm (Stryker 1472-5)',
  'Sternum Saw (Fine Tooth) 30.0 mm x 0.64 mm x 6.35 mm (Stryker 1472-6)',
  'STRYKER MixeVac 3 Cement Mixing System High Vacuum Kit, Sterile',
  'STRYKER Radiopaque Bone Cement, Full-Dose, For Accolade System,(1) 40 g Packet Powder, 20 mL 1 Ampoule',
  'STRYKER Revolution Cement Mixing System with Femoral Breakaway Nozzle and Medium Pressurizer',
  'STRYKER SafeAir Smoke Evacuation Pencil',
  'STRYKER Vertaplex HV Bone Cement, Domestic, Dual Pack',
  'STRYKER Vertaplex HV Bone Cement, Twin Pack',
  'Surgical Drape Sheets',
  'Surgical Drape Tape Strips',
  'Surgical Tray Corner Protectors',
  'SUTURE,BONE WAX,,NA,,UNDYED',
  'System 6 Heavy Duty Blade, 1.27 mm (Stryker 6221-127-90)',
  'System 6 Heavy Duty Blade, 18 mm x 1.19 mm x 100 mm (Stryker 6118-119-100)',
  'System 6 Heavy Duty Blade, 18 mm x 1.19 mm x 110 mm (Stryker 6118-119-110)',
  'System 6 Heavy Duty Blade, 18 mm x 1.27 mm x 100 mm (Stryker 6118-127-100)',
  'System 6 Heavy Duty Blade, 18 mm x 75 mm x 0.89 mm (Stryker 6118-089-075)',
  'System 6 Heavy Duty Blade, 18 mm x 90 mm x 1.19 mm (Stryker 6118-119-90)',
  'System 6 Heavy Duty Blade, 18 mm x 90 mm x 1.27 mm (Stryker 6118-127-90)',
  'System 6 Heavy Duty Sagittal Blade, 0.97 mm x 18 mm x 90 mm (Stryker 6118-97-90)',
  'System 6 Heavy Duty Saw Blade, 13 mm x 90 mm x 1.19 mm (Stryker 6113-119-090)',
  'System 6 Heavy, Duty Blade, 1.37 mm (Stryker 6221-137-090)',
  'System 6 Sagittal Blade, 13 mm x 90 mm 1.37 mm (Stryker 6113-137-90)',
  'System 6 Sagittal Blade, 18.mm x 90 mm x 1.37 mm (Stryker 6118-137-90)',
  'System 6 Sagittal Blade, 25.0 mm x 110.0 mm x 1.0 mm (Stryker 6125-100-110)',
  'System 6 Sagittal Saw Blade, 13 mm x 90 mm x 0.89 mm (Stryker 6113-89-90)',
  'System 6 Saw Blade, 100 mm x 25 mm x 1.27 (Stryker 6125-127-100)',
  'System 6 Saw Blade, 13 mm x 90 mm x 1.07 mm (Stryker 6113-107-90)',
  'System 6 Saw Blade, 75 mm x 25 mm x 0.89 mm (Stryker 6125-89-75)',
  'System 6 Saw Blade, 90 mm x 25 mm x 1.27 (Stryker 6125-127-90)',
  'System 6 Saw Blade, 90 mm x 25 mm x 1.27 mm (Stryker 6125-119-90)',
  'System 6 Sternum Blade, 30.5 mm x 1.0 mm (Stryker 6207-97-101)',
  'TIDI C-Armor Protective Barrier (Manufacturer: Tidi Products, LLC)',
  'TPS Crescentic Saw Blade Oscillating 18.5 mm x 32 mm x 0.38 mm (Stryker 2296-31-172)',
  'TPS Crescentic Saw Blade Oscillating, Teeth per cm: 1.3 13.5 mm x 32 mm x 0.38 mm (Stryker 2296-31-176)',
  'TPS Oscillating Blade Crescentic Micro 9.0 mm x 12 mm x 0.38 mm (Stryker 2296-31-170)',
  'TPS Oscillating Saw 18mmx.51mmx30 mm (Stryker 5400-031-417)',
  'TPS Oscillating Saw Crescentic Blade, 9.0 mm x 0.38 mm x 12.0 mm (Stryker 5400-031-170)',
  'TPS Oscillating Saw Crescentic Blade, 9.5 mm x 0.51 mm x 26.0 mm (Stryker 5400-031-415)',
  'TPS Oscillating Saw Sternotomy Blade, 53 mm x 0.38 mm (Stryker 5400-134-282)',
  'TPS Oscillating Saw, Sternotomy Blades 19.5 mm x 41.5 mm (Stryker 5400-134-415)',
  'TPS Oscillating Saw, Sternotomy Blades 54 mm x 40 mm (Stryker 5400-134-283)',
  'UltraGard Extremity T-Drapes',
  'UltraGard Laparotomy Drapes with Pouches',
  'UltraGard Standard Extremity Drapes',
  'V.A.C GRANUFOAM Bridge Dressing Kit with 1 (6 cm x 17 cm x 1.9 cm) Bridge Dressing with Integrated SENSAT.RAC. Pad, 1 Sheet of Perforated V.A.C Drape with Pre-Cut Hole and 1 Disposable Ruler',
  'V.A.C GRANUFOAM Large Dressing Kit with 1 (26 cm x 15 cm x 3.2 cm) Dressing, 2 Sheets of V.A.C Drape, 1 SENSAT.RAC. Pad with Connector and 1 Disposable Ruler',
  'V.A.C GRANUFOAM Medium Dressing Kit with 1 (18 cm x 12.5 cm x 3.2 cm) Dressing, 2 Sheets of V.A.C Drape, 1 SENSAT.RAC. Pad with Connector and 1 Disposable Ruler',
  'V.A.C GRANUFOAM Round Dressing Kit with 1 (5" Diameter) Dressing, 1 Sheet of V.A.C Drape, 1 SENSAT.RAC. Pad with Connector and 1 Disposable Ruler',
  'V.A.C GRANUFOAM Small Dressing Kit with 1 (10 cm x 7 cm x 3.2 cm) Dressing, 1 Sheet of V.A.C Drape, 1 SENSAT.RAC. Pad with Connector and 1 Disposable Ruler',
  'V.A.C. GranuFoam Silver Dressing Kit with 1 Large Dressing (26 x 15 x 3.2 cm)',
  'V.A.C. GranuFoam Silver Dressing Kit with 1 Medium Dressing (18 x 12.5 x 3.2 cm)',
  'V.A.C. GranuFoam Silver Dressing Kit with 1 Small Dressing (10 x 7.5 x 3.2 cm)',
  'Ventralight Mesh, Circle, Sterile, 6"',
  'Ventralight Mesh, Echo PS Positioning System, 7" x 9"',
  'Ventralight Mesh, Echo PS Positioning System, Oval, 6" x 10"',
  'Ventralight ST Mesh with Echo 2 PS Positioning System, 10 cm x 15 cm Ellipse',
  'Ventralight ST Mesh with Echo 2 PS Positioning System, 11 cm Circle',
  'Ventralight ST Mesh with Echo 2 PS Positioning System, 15 cm Circle',
  'Ventralight ST Mesh with Echo 2 PS Positioning System, 15 cm x 20 cm Ellipse',
  'Ventralight ST Mesh with Echo 2 PS Positioning System, 15 cm x 25 cm Ellipse',
  'Ventralight ST Mesh with Echo 2 PS Positioning System, 18 cm x 23 cm Ellipse',
  'Ventralight ST Mesh with Echo 2 PS Positioning System, 20 cm Circle',
  'Ventralight ST Mesh with Echo 2 PS Positioning System, 20 cm x 25 cm Ellipse',
  'Ventralight ST Mesh with Echo 2 PS Positioning System, 25 cm x 33 cm Ellipse',
  'Ventralight ST Mesh with Echo 2 PS Positioning System, 30 cm x 35 cm Ellipse',
  'Ventralight ST Mesh with Echo PS Positioning System',
  'Ventralight ST Mesh with Echo PS Positioning System, 12" x 14"',
  'Ventralight ST Mesh with Echo PS Positioning System, 4.5" Circle',
  'Ventralight ST Mesh with Echo PS Positioning System, 8" x 10" Ellipse',
  'Ventralight ST Mesh, 10" x 13" Ellipse',
  'Ventralight ST Mesh, 4" x 6" Ellipse',
  'Ventralight ST Mesh, 6" x 8" Ellipse',
  'Ventralight ST Mesh, 7" x 9" Ellipse',
  'Ventralight ST Mesh, 8" Circle',
  'Ventralight ST Mesh, 8" x 10" Ellipse',
  'Ventralight ST Permanent Mesh, 4.5" Circle',
  'Vessel Loops, White, Mini, Sterile, 0.8 x 762mm',
  'Vessel Loops, Yellow, Mini, Sterile, 0.8 x 762mm',
];



